FROM node:22-alpine

WORKDIR /app

# Copy package files first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose backend port
EXPOSE 3001

# Run nest start --watch in dev mode
CMD ["npm", "run", "start:dev"]
